### ISSUE TITLE
Fix the delete query in Employee Projects

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#35]
"Removing one row from managed employee projects permanently deletes all elements under that employee ID. I don’t know if that’s intentional."

**Comment by CupofJosiah** [comment]
This fix will be a bit annoying.

**Comment by nairnhoc** [comment]
This sounds like an error in my SQL query. I'll start looking into this...

**Comment by nairnhoc** [comment]
Very embarrassing; I forgot to add in the `project_id=project_not_worked_on` constraint in the `WHERE` clause the delete query. This would have made it so that a delete query would delete all projects that an employee 'X' worked on during the date `Y`, instead of simply deleting the single specific project that the manager knew the employee wasn't working on
