### ISSUE TITLE
Remove Deletion where not necessary

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#6]
Likely just employee and salary table. Do we even need deletion at all?

**Comment by nairnhoc** [comment]
Yeah, true deletion is very rare in this database. For employees, they are just marked as "inactive". For salaries, SQL queries will either retrieve an employee's current salary or the relevant salary in regards to calculating an employee's pay (the older or non-relevant salaries simply exist as a log of an employee's pay history).

The only case where deletion is relevant is in employee_projects. The idea behind this is that this table will contain data that is created by other employees. Because of this, though the data in the table will be structurally valid, some entries could be inaccurate or false (eg, an employee says they worked 12 hours on a project even though they only worked on it for 2 hours). Thus, deletion is used to get rid of these types of entries.

**Comment by CupofJosiah** [comment]
Let me know how you want to deal with it for roles and salaries

**Comment by nairnhoc** [comment]
For roles, my pitch would be for allowing deletion in cases where a role is associated with no employees, both active and inactive. That way, if somebody enters in a role which they later figure out nobody will use, they can go back and delete it without compromising the integrity of employee data.

As for the salaries, I think they're ok as-is. Even though it's really restrictive (can only INSERT entries, no DELETE or UPDATE), I think it's necessary for maintaining an accurate record of employee salary history, and I can't think of a way to allow an admin the ability to adjust mal-entered data without also opening up the door to allowing them to change arbitrary entries.

Though, now having said that...assuming employees are paid at the end of the month, allowing salary entries to be changed if they are within the current month wouldn't corrupt an employee's salary/payment history. I'll look into seeing if such a check is possible and reasonable.
